services:
  db:
    image: mysql:latest
    container_name: porm-db
    environment:
      MYSQL_DATABASE: porm-db
      MYSQL_ROOT_PASSWORD: 'strong_password'
    ports:
      - 3307:3306
    expose:
      - '3307'
    volumes:
      - porm-db:/var/lib/mysql
volumes:
  porm-db: